services:
  mysql:
    build: ./mysql/
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_sbm_vol:/var/lib/mysql
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - shared-net

  flyway_sbm_business:
    image: flyway/flyway:9
    command: -connectRetries=60 migrate
    volumes:
      - ./flyway/sql/sbm_business:/flyway/sql
      - ./flyway/sql/sbm_business/flyway.conf:/flyway/conf/flyway.conf
    depends_on:
      - mysql
    networks:
      - shared-net

  flyway_ditaly_pasta:
    image: flyway/flyway:9
    command: -connectRetries=60 migrate
    volumes:
      - ./flyway/sql/ditaly_pasta:/flyway/sql
      - ./flyway/sql/ditaly_pasta/flyway.conf:/flyway/conf/flyway.conf
    depends_on:
      - mysql
    networks:
      - shared-net

volumes:
  mysql_sbm_vol:

networks:
  shared-net:
    external: true