services:
  mysql:
    build: ./mysql/
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ./mysql_sbm_vol:/var/lib/mysql

  flyway:
    image: flyway/flyway:9
    command: -connectRetries=60 migrate
    volumes:
      - ./flyway/sql:/flyway/sql
      - ./flyway/flyway.conf:/flyway/conf/flyway.conf
    depends_on:
      - mysql
    environment:
      FLYWAY_USER: ${MYSQL_USER}
      FLYWAY_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  mysql_sbm_vol: