CREATE TABLE cataloge (
    id INT PRIMARY KEY AUTO_INCREMENT,
    sku VARCHAR(10) NOT NULL UNIQUE,
    menu INT NOT NULL,
    item_group INT NOT NULL,
    category INT NOT NULL,
    item_type INT NOT NULL,
    restriction INT NOT NULL,
    name VARCHAR(50) NOT NULL UNIQUE,
    description VARCHAR(150) NOT NULL,
    obs TEXT NOT NULL,
    usage_instructions INT NOT NULL,
    standard_gross_price INT NOT NULL DEFAULT 0,
    premium_gross_price INT NOT NULL DEFAULT 0,
    cover_image VARCHAR(2083) NULL,
    image_galery VARCHAR(2083) NULL,
    min_quantity_purchase INT NOT NULL DEFAULT 1,
    rations_quantity INT NOT NULL DEFAULT 1,
    configuration INT NOT NULL,
    is_visible TINYINT(1) NOT NULL DEFAULT 1,
    is_deleted TINYINT(1) NOT NULL DEFAULT 0,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NULL,
    deleted_at DATETIME NULL,
    created_by INT NOT NULL,
    updated_by INT NULL,
    deleted_by INT NULL,
    last_notification_at DATETIME NULL,
    is_confirmed TINYINT(1) NOT NULL DEFAULT 0,
    confirmed_at DATETIME NULL,
    confirmed_by INT NULL,
    version INT NOT NULL,
    log TEXT NOT NULL,
    FOREIGN KEY (menu) REFERENCES menu(id),
    FOREIGN KEY (usage_instructions) REFERENCES instruction(id),
    FOREIGN KEY (configuration) REFERENCES item_configuration(id)
);
