flyway.url=jdbc:mysql://mysql:3306/sbm_business?allowPublicKeyRetrieval=true&useSSL=false
flyway.user=sbmqa
flyway.password=FrancY1
flyway.schemas=sbm_business
flyway.locations=filesystem:/flyway/sql
flyway.baselineOnMigrate=true 