flyway.url=jdbc:postgresql://postgres:5432/sbm_db
flyway.user=sbm_user
flyway.password=sbm_password
flyway.schemas=sbm_business
flyway.locations=filesystem:/flyway/sql
flyway.validateMigrationNaming=true
flyway.baselineOnMigrate=true 