flyway.url=jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
flyway.user=${POSTGRES_USER}
flyway.password=${POSTGRES_PASSWORD}
flyway.schemas=${FLYWAY_SCHEMAS}
flyway.locations=filesystem:/flyway/sql
flyway.validateMigrationNaming=true
flyway.baselineOnMigrate=true
flyway.validateOnMigrate=true
flyway.cleanDisabled=false
flyway.encoding=UTF-8
flyway.placeholderReplacement=false 