flyway.url=jdbc:mysql://mysql:3306/ditaly_pasta?allowPublicKeyRetrieval=true&useSSL=false
flyway.user=sbmqa
flyway.password=FrancY1
flyway.schemas=ditaly_pasta
flyway.locations=filesystem:/flyway/sql
flyway.baselineOnMigrate=true 