CREATE SCHEMA IF NOT EXISTS ditaly_pasta;

CREATE TABLE IF NOT EXISTS ditaly_pasta.catalog (
    id int PRIMARY KEY AUTO_INCREMENT,
    code char(36) UNIQUE NULL COMMENT 'UUID() REQUIRES TRIGGER',
    sku varchar(50) NOT NULL,
    menu integer NOT NULL,
    `group` integer NOT NULL,
    category integer NOT NULL,
    `type` integer NOT NULL,
    restriction char(36) NOT NULL,
    name varchar(50) NOT NULL,
    description text NOT NULL,
    OBS varchar(255),
    chef_recommendation boolean NOT NULL DEFAULT 0,
    usage_instructions char(36) NOT NULL,
    base_gross_price integer NOT NULL DEFAULT 0,
    min_quantity_purchase integer NOT NULL DEFAULT 1,
    rations_quantity integer NOT NULL DEFAULT 1,
    cover_image varchar(2083),
    secondary_image varchar(2083),
    complementary_image varchar(2083),
    image_gallery varchar(2083),
    configuration char(36) NOT NULL,
    is_visible boolean NOT NULL DEFAULT 1,
    is_deleted boolean,
    is_confirmed boolean,
    created_at datetime DEFAULT (CURRENT_TIMESTAMP),
    updated_at datetime,
    confirmed_at datetime,
    deleted_at datetime,
    created_by char(36) NOT NULL,
    confirmed_by char(36),
    updated_by char(36),
    deleted_by char(36),
    `LOG` text NOT NULL,
    version integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS ditaly_pasta.item_configuration (
    id int PRIMARY KEY AUTO_INCREMENT,
    code char(36) UNIQUE NOT NULL COMMENT 'UUID() REQUIRES TRIGGER',
    configuration varchar(50) NOT NULL,
    description text NOT NULL,
    package integer NOT NULL,
    is_deleted boolean,
    is_confirmed boolean,
    created_at datetime DEFAULT (CURRENT_TIMESTAMP),
    updated_at datetime,
    confirmed_at datetime,
    deleted_at datetime,
    created_by char(36) NOT NULL,
    confirmed_by char(36),
    updated_by char(36),
    deleted_by char(36),
    LOG text NOT NULL,
    version integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS ditaly_pasta.item_configuration_detail (
    id integer PRIMARY KEY AUTO_INCREMENT,
    code char(36) NOT NULL,
    detail varchar(50) NOT NULL,
    type integer NOT NULL,
    configuration char(36) NOT NULL,
    id_item char(36) NOT NULL,
    is_deleted boolean,
    is_confirmed boolean,
    created_at datetime DEFAULT (CURRENT_TIMESTAMP),
    updated_at datetime,
    confirmed_at datetime,
    deleted_at datetime,
    created_by char(36) NOT NULL,
    confirmed_by char(36),
    updated_by char(36),
    deleted_by char(36)
);

CREATE TABLE IF NOT EXISTS ditaly_pasta.product (
    id integer PRIMARY KEY AUTO_INCREMENT,
    code char(36) UNIQUE NOT NULL COMMENT 'UUID() REQUIRES TRIGGER',
    sku varchar(50) NOT NULL,
    description text NOT NULL,
    OBS text NOT NULL,
    package_unit integer NOT NULL,
    min_package_purchase integer NOT NULL,
    gross_price integer NOT NULL DEFAULT 0,
    provider integer NOT NULL,
    `type` integer NOT NULL,
    `group` integer NOT NULL,
    category integer NOT NULL,
    url varchar(255),
    package integer NOT NULL,
    is_active boolean NOT NULL DEFAULT 1,
    is_deleted boolean,
    is_confirmed boolean,
    created_at datetime DEFAULT (CURRENT_TIMESTAMP),
    updated_at datetime,
    confirmed_at datetime,
    deleted_at datetime,
    created_by char(36) NOT NULL,
    confirmed_by char(36),
    updated_by char(36),
    deleted_by char(36),
    `LOG` text NOT NULL,
    version integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS ditaly_pasta.material (
    id integer PRIMARY KEY AUTO_INCREMENT,
    code char(36) UNIQUE NOT NULL COMMENT 'UUID() REQUIRES TRIGGER',
    sku varchar(50) NOT NULL,
    description text NOT NULL,
    OBS text NOT NULL,
    package_unit integer NOT NULL,
    min_package_purchase integer NOT NULL,
    gross_price integer NOT NULL DEFAULT 0,
    provider integer NOT NULL,
    `type` integer NOT NULL,
    `group` integer NOT NULL,
    category integer NOT NULL,
    url varchar(255),
    package integer NOT NULL,
    is_active boolean NOT NULL DEFAULT 1,
    is_deleted boolean,
    is_confirmed boolean,
    created_at datetime DEFAULT (CURRENT_TIMESTAMP),
    updated_at datetime,
    confirmed_at datetime,
    deleted_at datetime,
    created_by char(36) NOT NULL,
    confirmed_by char(36),
    updated_by char(36),
    deleted_by char(36),
    `LOG` text NOT NULL,
    version integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS ditaly_pasta.service (
    id integer PRIMARY KEY AUTO_INCREMENT,
    code char(36) UNIQUE NOT NULL COMMENT 'UUID() REQUIRES TRIGGER',
    sku varchar(50) NOT NULL,
    description text NOT NULL,
    OBS text NOT NULL,
    package_unit integer NOT NULL,
    min_package_purchase integer NOT NULL,
    gross_price integer NOT NULL DEFAULT 0,
    provider integer NOT NULL,
    `type` integer NOT NULL,
    `group` integer NOT NULL,
    category integer NOT NULL,
    url varchar(255),
    is_active boolean NOT NULL DEFAULT 1,
    is_deleted boolean,
    is_confirmed boolean,
    created_at datetime DEFAULT (CURRENT_TIMESTAMP),
    updated_at datetime,
    confirmed_at datetime,
    deleted_at datetime,
    created_by char(36) NOT NULL,
    confirmed_by char(36),
    updated_by char(36),
    deleted_by char(36),
    `LOG` text NOT NULL,
    version integer NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS ditaly_pasta.provider (
    id integer PRIMARY KEY AUTO_INCREMENT,
    code char(36) UNIQUE NOT NULL COMMENT 'CUSTOM TRIGGER',
    provider varchar(50) UNIQUE NOT NULL,
    `type` integer NOT NULL,
    rating integer NOT NULL DEFAULT 0,
    OBS_provider text NOT NULL,
    contact_name varchar(100),
    contact_mail varchar(255),
    contact_phone bigint,
    contact_phone2 bigint,
    website_url text,
    OBS_contact varchar(255),
    company_name varchar(255),
    company_rut varchar(12),
    company_activity varchar(255),
    legal_representative varchar(255),
    billing_address text,
    billing_mail varchar(255),
    billing_phone bigint,
    company_bank integer,
    bank_account_type integer,
    bank_account_number varchar(255),
    bank_account_mail varchar(255),
    dispatch_address varchar(255),
    dispatch_maps_location varchar(255),
    OBS_dispatch text,
    dispatch_district integer,
    dispatch_region integer,
    is_active boolean NOT NULL DEFAULT 1,
    is_deleted boolean,
    is_confirmed boolean,
    created_at datetime DEFAULT (CURRENT_TIMESTAMP),
    updated_at datetime,
    confirmed_at datetime,
    deleted_at datetime,
    created_by char(36) NOT NULL,
    confirmed_by char(36),
    updated_by char(36),
    deleted_by char(36),
    `LOG` text NOT NULL,
    version integer NOT NULL DEFAULT 1
); 