flyway.url=jdbc:mysql://mysql:3306/sbmbusiness?allowPublicKeyRetrieval=true&useSSL=false
flyway.user=${FLYWAY_USER}
flyway.password=${FLYWAY_PASSWORD}
flyway.locations=filesystem:/flyway/sql
flyway.defaultSchema=sbmbusiness
flyway.baselineOnMigrate=true
